<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Import Project="..\..\Framework\Birko.Time\Birko.Time.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Serialization\Birko.Serialization.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Data.Core\Birko.Data.Core.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Data.Stores\Birko.Data.Stores.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Data.Repositories\Birko.Data.Repositories.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Data.SQL\Birko.Data.SQL.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Data.SQL.View\Birko.Data.SQL.View.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Data.Patterns\Birko.Data.Patterns.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Rules\Birko.Rules.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Models.Contracts\Birko.Models.Contracts.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Models\Birko.Models.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Models.SQL\Birko.Models.SQL.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Models.Inventory\Birko.Models.Inventory.projitems" Label="Shared" />
  <Import Project="..\..\Framework\Birko.Models.Inventory.SQL\Birko.Models.Inventory.SQL.projitems" Label="Shared" />

</Project>
